routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $user = auth()->user();
    if ($user->isAdmin()) {
        return view('admin.dashboard');
    }
    return view('admin.profile.index', compact('user'));
});

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::get('/profile', 'AdminController@profile')->name('profile');

    Route::get('/all-demand', 'DemandController@allDemands')->name('allDemands');
    Route::post('/demand/change-state', 'DemandController@changeState')->name('changeState');
    Route::post('/demand/change-state-multiple', 'DemandController@changeStateMultiple')->name('changeStateMultiple');

    Route::resource('demands', 'DemandController');
    Route::get('/demand/{demand}/download', 'DemandController@download')->name('download');

    Route::resource('states', 'StateController');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/State.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class State extends Model
{
    protected $fillable = ['name'];

    public function demands()
    {
        return $this->belongsToMany(Demand::class);
    }
}

app/Http/Controllers/StateController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StateRequest;
use App\State;
use Illuminate\Http\Request;

class StateController extends Controller
{


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $states = State::all();
        return view('admin.states.index', compact('states'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.states.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StateRequest $request)
    {
        State::create(['name' => $request->name]);
        return back()->with('message', 'وضعیت جدید ثبت شد');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function show(State $state)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function edit(State $state)
    {
        return view('admin.states.edit', compact('state'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function update(StateRequest $request, State $state)
    {
        $state->update(['name' => $request->name]);
        return redirect(route('states.index'))->with('message', 'وضعیت ویرایش شد');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\State  $state
     * @return \Illuminate\Http\Response
     */
    public function destroy(State $state)
    {
        $state->delete();
        return back()->with('message', 'وضعیت حذف شد');
    }
}

resources/views/admin/states/edit.blade.php
@extends('admin.layout.master')
@section('content')
<div class="col-md-12 grid-margin stretch-card">
<div class="card my-4">
   <div class="card-body">
    <form method="POST" action="{{route('states.update', $state->id)}}">
        @csrf
        @method('PATCH')
        @include('includes.errors')
        @include('includes.flash')
        <div class="form-group">
            <label for="name">عنوان</label>
            <input type="text" class="form-control" id="name" name="name" value="{{$state->name}}" placeholder="نام را وارد کنید..">
        </div>
        <button type="submit" class="btn btn-primary">ویرایش وضعیت</button>
    </form>
  </div>
</div>
</div>
@endsection

resources/views/admin/states/index.blade.php
@extends('admin.layout.master')
@section('content')

<div class="col-md-12 grid-margin stretch-card">
@include('includes.errors')
@include('includes.flash')
<div class="card my-4">
   <div class="card-body">
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">نام</th>
            <th scope="col">تنظیمات</th>
        </tr>
        </thead>
        <tbody>
        @if($states)
            @foreach($states as $state)

                <tr>
                    <td>{{$state->name}}</td>
                    <td>
                        <form action="{{route('states.destroy', $state->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-sm btn-danger">
                                <svg class="bi bi-trash" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </button>
                            <a href="{{route('states.edit', $state->id)}}" class="btn btn-sm btn-primary">
                                <svg class="bi bi-pencil-square" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                                    <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                 </svg>
                            </a>
                        </form>
                    </td>
                </tr>

            @endforeach
        @endif
        </tbody>
    </table>
    </div>
</div>


<div class="card">
   <div class="card-body">
        <form method="POST" action="{{route('states.store')}}">
                @csrf

                <div class="form-group">
                    <label for="name">عنوان</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ old('name') and $state->name}}" placeholder="نام را وارد کنید..">
                </div>
                <button type="submit" class="btn btn-primary">ثبت وضعیت</button>
            </form>
       </div>
   </div>
   </div>
@endsection