routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $user = auth()->user();
    if ($user->isAdmin()) {
        return view('admin.dashboard');
    }
    return view('admin.profile.index', compact('user'));
});

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');
    Route::get('/profile', 'AdminController@profile')->name('profile');

    Route::get('/all-demand', 'DemandController@allDemands')->name('allDemands');
    Route::post('/demand/change-state', 'DemandController@changeState')->name('changeState');
    Route::post('/demand/change-state-multiple', 'DemandController@changeStateMultiple')->name('changeStateMultiple');

    Route::resource('demands', 'DemandController');
    Route::get('/demand/{demand}/download', 'DemandController@download')->name('download');

    Route::resource('states', 'StateController');
});



Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Start layout styles -->

    <link rel="stylesheet" href="http://cdn.materialdesignicons.com/5.1.45/css/materialdesignicons.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('css/app.css')}}" />
    <!-- End layout styles -->
    <title>داشبورد</title>
</head>

<body class="rtl">
    <!-- Miscellanoeous  Miscellaneous-->
    <div class="container-scroller">
        <!-- navbar starts here -->
        @include('admin.layout.nav')
        <!-- ends here -->
        <div class="container-fluid page-body-wrapper">
            <!-- settings-panel starts here -->
            <!-- sidebar starts here -->
            @include('admin.layout.sidebar')
            <!-- ends here -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        @yield('content')
                    </div>
                </div>
                <!-- content-wrapper ends -->
                <!-- footer starts here-->
                <footer class="footer">
                    <div class="d-sm-flex justify-content-center justify-content-sm-between">
                        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">سیستم مدیریت © 2020
                        </span>
                        {{-- <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">ساخته شده توسط <i
                                class="mdi mdi-heart text-danger"></i></span> --}}
                    </div>
                </footer>
                <!-- ends here -->
            </div>
            <!-- main-panel ends -->
        </div>
        <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->

    <!-- Jquery & Popper & Bootstrap:js -->
    <script src="{{asset('js/app.js')}}"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#datatable').DataTable();
        });

    </script>
    @yield('scripts')
    <!-- endinject -->
</body>

</html>

resources/views/admin/layout/nav.blade.php
<nav
    class="navbar default-layout-navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row"
>
    <div
        class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center"
    >
        <div
            class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center"
        >
            <a class="navbar-brand brand-logo" href=""
            ><img
                    src="https://laravel.com/img/logotype.min.svg"
                    alt="logo" /><img
                    src="https://laravel.com/img/logomark.min.svg"
                    alt="logo"
                /></a>
            <a class="navbar-brand brand-logo-mini" href="/"
            ><img src="https://laravel.com/img/logomark.min.svg" alt="logo"
                /></a>
        </div>
    </div>
    <div class="navbar-menu-wrapper d-flex align-items-stretch">
        <button
            class="navbar-toggler navbar-toggler align-self-center"
            type="button"
            data-toggle="minimize"
        >
            <span class="mdi mdi-menu"></span>
        </button>
        <div class="search-field d-none d-md-block">
            <form class="d-flex align-items-center h-100" action="#">
                <div class="input-group d-flex align-items-center">
                    <div class="input-group-prepend bg-transparent">
                        <i class="input-group-text border-0 mdi mdi-magnify"></i>
                    </div>
                    <input
                        type="text"
                        class="form-control bg-transparent border-0"
                        placeholder="جست وجو"
                    />
                </div>
            </form>
        </div>
        <ul class="navbar-nav navbar-nav-right pr-0">
            <li class="nav-item nav-profile dropdown">
                <a
                    class="nav-link dropdown-toggle"
                    id="profileDropdown"
                    href="#"
                    data-toggle="dropdown"
                    aria-expanded="false"
                >
                    <div class="nav-profile-img">
                        <img
                            src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                            alt="image"
                        />
                        <span class="availability-status online"></span>
                    </div>
                    <div class="nav-profile-text">
                        <p class="mb-1 text-black">مرتضی بابانژاد</p>
                    </div>
                </a>
                <div
                    class="dropdown-menu navbar-dropdown text-right"
                    aria-labelledby="profileDropdown"
                >
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-cached mr-2 text-success"></i> پنل کاربری
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">
                        <i class="mdi mdi-logout mr-2 text-primary"></i> خروج
                    </a>
                </div>
            </li>
            <!-- <li class="nav-item d-none d-lg-block full-screen-link">
              <a class="nav-link">
                <i class="mdi mdi-fullscreen" id="fullscreen-button"></i>
              </a>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link count-indicator dropdown-toggle"
                id="messageDropdown"
                href="#"
                data-toggle="dropdown"
                aria-expanded="false"
              >
                <i class="mdi mdi-email-outline"></i>
                <span class="count-symbol bg-warning"></span>
              </a>
              <div
                class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
                aria-labelledby="messageDropdown"
              >
                <h6 class="p-3 mb-0 text-right">پیام ها</h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img
                      src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                      alt="image"
                      class="profile-pic"
                    />
                  </div>
                  <div
                    class="preview-item-content d-flex align-items-start flex-column justify-content-center"
                  >
                    <h6
                      class="preview-subject ellipsis mb-1 font-weight-normal"
                    >
                      عالی بود
                    </h6>
                    <p class="text-gray mb-0">6 دقیقه قبل</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img
                      src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                      alt="image"
                      class="profile-pic"
                    />
                  </div>
                  <div
                    class="preview-item-content d-flex align-items-start flex-column justify-content-center"
                  >
                    <h6
                      class="preview-subject ellipsis mb-1 font-weight-normal"
                    >
                      عالی بود
                    </h6>
                    <p class="text-gray mb-0">15 دقیقه قبل</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img
                      src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                      alt="image"
                      class="profile-pic"
                    />
                  </div>
                  <div
                    class="preview-item-content d-flex align-items-start flex-column justify-content-center"
                  >
                    <h6
                      class="preview-subject ellipsis mb-1 font-weight-normal"
                    >
                      عالی عالی عالی عالیالی عالی عالی عالیالی عالی عالی عالیالی
                      عالی عالی عالیالی عالی عالی عالیالی عالی عالی عالی عالی
                      بود
                    </h6>
                    <p class="text-gray mb-0">15 دقیقه قبل</p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <h6 class="p-3 mb-0 text-center">
                  <a href="">مشاهده همه پیام ها</a>
                </h6>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a
                class="nav-link count-indicator dropdown-toggle"
                id="notificationDropdown"
                href="#"
                data-toggle="dropdown"
              >
                <i class="mdi mdi-bell-outline"></i>
                <span class="count-symbol bg-danger"></span>
              </a>
              <div
                class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
                aria-labelledby="notificationDropdown"
              >
                <h6 class="p-3 mb-0 text-right">خطاها</h6>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-success">
                      <i class="mdi mdi-calendar"></i>
                    </div>
                  </div>
                  <div
                    class="preview-item-content d-flex align-items-start flex-column justify-content-center"
                  >
                    <h6
                      class="preview-subject font-weight-normal mb-1 text-danger"
                    >
                      عدم نمایش تاریخ
                    </h6>
                    <p class="text-gray ellipsis mb-0">
                      در مقاله با ایدی 9 تاریخ نمایش داده نمی شود
                    </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-warning">
                      <i class="mdi mdi-settings"></i>
                    </div>
                  </div>
                  <div
                    class="preview-item-content d-flex align-items-start flex-column justify-content-center"
                  >
                    <h6
                      class="preview-subject font-weight-normal mb-1 text-danger"
                    >
                      عدم نمایش تاریخ
                    </h6>
                    <p class="text-gray ellipsis mb-0">
                      در مقاله با ایدی 9 تاریخ نمایش داده نمی شود
                    </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <div class="preview-icon bg-info">
                      <i class="mdi mdi-link-variant"></i>
                    </div>
                  </div>
                  <div
                    class="preview-item-content d-flex align-items-start flex-column justify-content-center"
                  >
                    <h6
                      class="preview-subject font-weight-normal mb-1 text-danger"
                    >
                      عدم نمایش تاریخ
                    </h6>
                    <p class="text-gray ellipsis mb-0">
                      در مقاله با ایدی 9 تاریخ نمایش داده نمی شود
                    </p>
                  </div>
                </a>
                <div class="dropdown-divider"></div>
                <h6 class="p-3 mb-0 text-center">
                  <a href="">مشاهده همه خطاها</a>
                </h6>
              </div>
            </li>
            <li class="nav-item nav-logout d-none d-lg-block">
              <a class="nav-link" href="#">
                <i class="mdi mdi-power"></i>
              </a>
            </li>
            <li class="nav-item nav-settings d-none d-lg-block">
              <a class="nav-link" href="#">
                <i class="mdi mdi-format-line-spacing"></i>
              </a>
            </li> -->
        </ul>
        <button
            class="navbar-toggler navbar-toggler-right d-lg-none align-self-center"
            type="button"
            data-toggle="offcanvas"
        >
            <span class="mdi mdi-menu"></span>
        </button>
    </div>
</nav>

resources/views/admin/layout/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <ul class="nav">
        <li class="nav-item nav-profile">
            <a href="#" class="nav-link">
                <div class="nav-profile-image">
                    <img src="https://raw.githubusercontent.com/azouaoui-med/pro-sidebar-template/gh-pages/src/img/user.jpg"
                        alt="profile" />
                    <span class="login-status online"></span>
                    <!--change to offline or busy as needed-->
                </div>
                <div class="nav-profile-text d-flex flex-column">
                    <span class="font-weight-bold mb-2">مرتضی بابانژاد</span>
                    <span class="text-secondary text-small">مدير سایت</span>
                </div>
                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>
            </a>
        </li>
        @can('manage', auth()->user())
        <li class="nav-item">
            <a class="nav-link" href="{{route('dashboard')}}">
                <span class="menu-title">داشبورد</span>
                <i class="mdi mdi-home menu-icon"></i>
            </a>
        </li>
        @endcan
        <li class="nav-item">
            <a class="nav-link" href="{{route('profile')}}">
                <span class="menu-title">پروفایل</span>
                <i class="mdi menu-icon">
                    <svg class="bi bi-person-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                    </svg>
                </i>
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{route('demands.create')}}">
                <span class="menu-title">ثبت درخواست</span>
                <i class="mdi menu-icon">
                    <svg class="bi bi-pencil" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z" />
                        <path fill-rule="evenodd"
                            d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 0 0 .5.5H4v.5a.5.5 0 0 0 .5.5H5v.5a.5.5 0 0 0 .5.5H6v-1.5a.5.5 0 0 0-.5-.5H5v-.5a.5.5 0 0 0-.5-.5H3z" />
                    </svg>
                </i>
            </a>
        </li>
        @can('manage', auth()->user())
        <li class="nav-item">
            <a class="nav-link" href="{{route('allDemands')}}">
                <span class="menu-title">درخواست ها</span>
                <i class="mdi menu-icon">
                    <svg class="bi bi-pencil" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z" />
                        <path fill-rule="evenodd"
                            d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 0 0 .5.5H4v.5a.5.5 0 0 0 .5.5H5v.5a.5.5 0 0 0 .5.5H6v-1.5a.5.5 0 0 0-.5-.5H5v-.5a.5.5 0 0 0-.5-.5H3z" />
                    </svg>
                </i>
            </a>
        </li>


        <li class="nav-item">
            <a class="nav-link" href="{{route('states.index')}}">
                <span class="menu-title">وضعیت ها</span>
                <i class="mdi menu-icon">
                    <svg class="bi bi-list-check" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor"
                        xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd"
                            d="M5 11.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3.854 2.146a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708L2 3.293l1.146-1.147a.5.5 0 0 1 .708 0zm0 4a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 1 1 .708-.708L2 7.293l1.146-1.147a.5.5 0 0 1 .708 0zm0 4a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0l-.5-.5a.5.5 0 0 1 .708-.708l.146.147 1.146-1.147a.5.5 0 0 1 .708 0z" />
                    </svg>
                </i>
            </a>
        </li>
        @endcan
        <!-- <li class="nav-item">
          <a
            class="nav-link"
            data-toggle="collapse"
            href="#apps"
            aria-expanded="false"
            aria-controls="apps"
          >
            <span class="menu-title">فروشگاه</span>
            <i class="menu-arrow"></i>
            <i class="mdi mdi-cart-arrow-down menu-icon"></i>
          </a>
          <div class="collapse" id="apps">
            <ul class="nav flex-column sub-menu">
              <li class="nav-item">
                <a
                  class="nav-link"
                  href="../../pages/apps/kanban-board.html"
                  >همه محصولات</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="../../pages/apps/todo.html"
                  >ثبت محصول جدید</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="../../pages/apps/tickets.html"
                  >روش ارسال کالا</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="../../pages/apps/chats.html"
                  >کوپن تخفیف</a
                >
              </li>
            </ul>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="../../pages/samples/widgets.html">
            <span class="menu-title">تنظیمات</span>
            <i class="mdi mdi-forum menu-icon"></i>
          </a>
        </li> -->
    </ul>
</nav>